// <auto-generated />
using System;
using CloudReports.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudReports.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CloudReportsDbContext))]
    [Migration("20261007142547_CoverChartQueryIndex")]
    partial class CoverChartQueryIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudReports.Domain.Entities.FetchLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<long?>("WeatherReadingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAtUtc");

                    b.HasIndex("WeatherReadingId");

                    b.HasIndex("City", "AttemptedAtUtc");

                    b.ToTable("FetchLogs", (string)null);
                });

            modelBuilder.Entity("CloudReports.Domain.Entities.WeatherReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAtUtc", "City");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("FetchedAtUtc", "City"), new[] { "Country", "ObservedAtUtc", "Temperature", "TemperatureMin", "TemperatureMax" });

                    b.ToTable("WeatherReadings", (string)null);
                });

            modelBuilder.Entity("CloudReports.Domain.Entities.FetchLog", b =>
                {
                    b.HasOne("CloudReports.Domain.Entities.WeatherReading", "WeatherReading")
                        .WithMany()
                        .HasForeignKey("WeatherReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WeatherReading");
                });
#pragma warning restore 612, 618
        }
    }
}
